import turtle


wn = turtle.Screen()
alex = turtle.Turtle()
alex.pensize(4)
alex.shape("turtle")
alex.speed(5)

alex.up()
alex.backward(280)

alex.color("red")
#Drawing A
alex.down()
alex.left(90)
alex.forward(50)
alex.right(90)
alex.forward(20)
alex.right(90)
alex.forward(50)
alex.left(180)
alex.up()
alex.forward(25)
alex.left(90)
alex.down()
alex.forward(20)
alex.left(90)
alex.up()
alex.forward(25)
alex.left(90)
alex.forward(30)

#Creating new environment
wn.bgcolor("light green")
alex.color("violet")
#Drawing L
alex.down()
alex.left(90)
alex.forward(50)
alex.up()
alex.right(180)
alex.forward(50)
alex.left(90)
alex.down()
alex.forward(30)
alex.up()
alex.forward(10)

#Creating new environment
wn.bgcolor("light yellow")
alex.color("pink")
#Drawing I
alex.down()
alex.left(90)
alex.forward(50)
alex.right(180)
alex.up()
alex.forward(50)
alex.left(90)
alex.forward(30)

#Creating new environment
wn.bgcolor("lightblue")
alex.color("brown")
#Drawing H
alex.down()
alex.left(90)
alex.forward(50)
alex.right(180)
alex.up()
alex.forward(25)
alex.left(90)
alex.down()
alex.forward(20)
alex.left(90)
alex.forward(25)
alex.up()
alex.backward(25)
alex.down()
alex.backward(25)
alex.right(90)
alex.up()
alex.forward(10)

#Creating new environment
wn.bgcolor("white")
alex.color("red")
#Drawing A
alex.down()
alex.left(90)
alex.forward(50)
alex.right(90)
alex.forward(20)
alex.right(90)
alex.forward(50)
alex.left(180)
alex.up()
alex.forward(25)
alex.left(90)
alex.down()
alex.forward(20)
alex.left(90)
alex.up()
alex.forward(25)
alex.left(90)
alex.forward(30)

#Creating new environment
wn.bgcolor("wheat")
alex.color("teal")
#Drawing S
for _ in range(2):
    alex.down()
    alex.forward(20)
    alex.left(90)
    alex.forward(25)
    alex.left(90)
    alex.forward(20)
    alex.right(90)
    alex.forward(25)
    alex.right(90)
    alex.forward(20)
    alex.up()
    alex.forward(10)
    alex.right(90)
    alex.forward(50)
    alex.left(90)
    wn.bgcolor("white smoke")
    alex.color("sandy brown")

#Creating new Environment
wn.bgcolor("azure")
alex.color("light coral")
#Drawing A
alex.down()
alex.left(90)
alex.forward(50)
alex.right(90)
alex.forward(20)
alex.right(90)
alex.forward(50)
alex.left(180)
alex.up()
alex.forward(25)
alex.left(90)
alex.down()
alex.forward(20)
alex.left(90)
alex.up()
alex.forward(25)
alex.left(90)
alex.forward(30)

#Creating new Environment
wn.bgcolor("mint cream")
alex.color("aquamarine")
#Drawing N
alex.down()
alex.left(90)
alex.forward(50)
alex.right(150)
alex.forward(58)
alex.left(150)
alex.forward(50)
alex.up()
alex.backward(50)
alex.right(90)
alex.forward(10)

alex.forward(150)
wn.bgcolor("white")
alex.color("red")
distance = 40
for _ in range(10):
    alex.stamp()
    alex.left(75)
    alex.forward(distance)
    distance = distance + 10

turtle.exitonclick()